metadata:
  device : 'cpu'
  saved_model_path : 'archive/model'
  tensor_path : 'archive/B.%20Disease%20Grading/B. Disease Grading/3. Tensor Images'

image_preprocessing:
  image_size : 224
  itype : '.jpg' # image type
  batch_size : 16
  shuffle : True
  do_random_crop : True
  columns : ['Image name', 'Retinopathy grade']

train_dataset:

  image_path: 'dataset/train/'
  label_path: 'dataset/train.csv'

test_dataset:

  image_path: 'dataset/test/'
  label_path: 'dataset/test.csv'

model:
  name: 'efficientnet-b0'
  pretrained: True
  num_classes: 5
  return_nodes: ['features.3.6.add']