metadata:
  device : 'cuda:0'
  saved_model_path : 'archive/model'
  tensor_path : 'archive/B.%20Disease%20Grading/B. Disease Grading/3. Tensor Images'

image_preprocessing:
  image_size : 224
  itype : '.jpg' # image type
  batch_size : 16
  shuffle : True
  do_random_crop : True
  columns : ['Image name', 'Retinopathy grade']

train_dataset:
  columns: ['Image name', 'Retinopathy grade']
  image_path: 'archive/B.%20Disease%20Grading/B. Disease Grading/1. Original Images/a. Training Set'
  label_path: 'archive/B.%20Disease%20Grading/B. Disease Grading/2. Groundtruths/a. IDRiD_Disease Grading_Training Labels.csv'
  do_random_crop : True
  shuffle: True
  batch_size: 16

test_dataset:
  columns: ['Image name', 'Retinopathy grade']
  image_path: 'archive/B.%20Disease%20Grading/B. Disease Grading/1. Original Images/b. Testing Set'
  label_path: 'archive/B.%20Disease%20Grading/B. Disease Grading/2. Groundtruths/b. IDRiD_Disease Grading_Testing Labels.csv'
  do_random_crop : False
  shuffle: False
  batch_size: 16

model:
  name: 'efficientnet-b0'
  pretrained: True
  num_classes: 5
  return_nodes: ['features.3.6.add']